/**
 * HTMLRenderer Component
 * Generates self-contained HTML portfolio pages from portfolio data
 * Source: architecture/components.md#HTMLRenderer Component
 */

import {
  PortfolioData,
  IPAssetWithRelationships,
} from '../types/portfolio.js';
import { truncateIpId } from './graph-builder.js';

/**
 * GitHub repository URL placeholder
 * Update when actual URL is confirmed
 */
const GITHUB_REPO_URL = 'https://github.com/storyprotocol/story-cli';

/**
 * Render options for fallback visualization
 */
export interface HTMLRenderOptions {
  svgFallback?: string;
  htmlFallback?: string;
}

/**
 * Extended portfolio data with optional Mermaid diagram
 */
export type PortfolioDataWithMermaid = PortfolioData & {
  mermaidDiagram?: string;
};

/**
 * Escape HTML special characters to prevent XSS attacks
 * Escapes <, >, &, ", and ' characters
 *
 * @param text - Raw text to escape
 * @returns HTML-safe escaped string
 */
export function escapeHtml(text: string): string {
  const htmlEscapes: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  };
  return text.replace(/[&<>"']/g, (char) => htmlEscapes[char]);
}

/**
 * Format ISO date string to human-readable format
 * e.g., "Nov 25, 2025, 3:45 PM"
 *
 * @param isoDate - ISO 8601 date string
 * @returns Human-readable date string
 */
export function formatDate(isoDate: string): string {
  const date = new Date(isoDate);
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  });
}

/**
 * Format date for footer (without time)
 *
 * @param isoDate - ISO 8601 date string
 * @returns Human-readable date string without time
 */
function formatFooterDate(isoDate: string): string {
  const date = new Date(isoDate);
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

/**
 * Truncate wallet address for display
 *
 * @param address - Full wallet address
 * @returns Truncated address (0x1234...5678)
 */
function truncateWalletAddress(address: string): string {
  if (address.length <= 12) return address;
  return `${address.slice(0, 6)}...${address.slice(-4)}`;
}

/**
 * HTMLRenderer class for generating self-contained HTML portfolio pages
 */
export class HTMLRenderer {
  /**
   * Render complete HTML portfolio page
   *
   * @param portfolioData - Portfolio data with optional Mermaid diagram
   * @param options - Optional fallback visualization options
   * @returns Complete HTML document string
   */
  render(
    portfolioData: PortfolioDataWithMermaid,
    options?: HTMLRenderOptions
  ): string {
    const {
      walletAddress,
      network,
      assets,
      statistics,
      generatedAt,
      mermaidDiagram,
    } = portfolioData;

    const graphSection = this.renderGraphSection(
      mermaidDiagram,
      options?.svgFallback,
      options?.htmlFallback
    );

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>IP Portfolio - ${escapeHtml(truncateWalletAddress(walletAddress))}</title>
  ${this.getEmbeddedStyles()}
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
</head>
<body>
  <header>
    <h1>IP Portfolio</h1>
    <p class="wallet">${escapeHtml(truncateWalletAddress(walletAddress))}</p>
    <span class="network-badge">${escapeHtml(network)}</span>
  </header>

  <section class="statistics">
    <h2>Portfolio Statistics</h2>
    <div class="stats-grid">
      ${this.renderStatisticsCard('Total Assets', statistics.totalAssets)}
      ${this.renderStatisticsCard('Root Assets', statistics.rootAssets)}
      ${this.renderStatisticsCard('Derivatives', statistics.derivatives)}
      ${this.renderStatisticsCard('Licenses Issued', statistics.licensesIssued)}
      ${this.renderStatisticsCard('Total Royalties', `${statistics.totalRoyalties} IP`)}
    </div>
  </section>

  <section class="graph">
    <h2>Relationship Graph</h2>
    ${graphSection}
  </section>

  <section class="assets">
    <h2>IP Assets</h2>
    ${this.renderAssetTable(assets)}
  </section>

  <footer>
    Generated by <a href="${GITHUB_REPO_URL}">Story CLI</a> on ${formatFooterDate(generatedAt)}
  </footer>

  ${this.getEmbeddedScript()}
</body>
</html>`;
  }

  /**
   * Render graph section with Mermaid diagram or fallbacks
   *
   * @param mermaidDiagram - Mermaid diagram syntax
   * @param svgFallback - Optional SVG fallback
   * @param htmlFallback - Optional HTML list fallback
   * @returns HTML string for graph section content
   */
  private renderGraphSection(
    mermaidDiagram?: string,
    svgFallback?: string,
    htmlFallback?: string
  ): string {
    if (mermaidDiagram && mermaidDiagram.trim() !== '') {
      return `<div class="mermaid">${mermaidDiagram}</div>`;
    }

    if (svgFallback && svgFallback.trim() !== '') {
      return `<div class="svg-fallback">${svgFallback}</div>`;
    }

    if (htmlFallback && htmlFallback.trim() !== '') {
      return `<div class="html-fallback">${htmlFallback}</div>`;
    }

    return '<div class="no-graph"><p>Graph visualization unavailable</p></div>';
  }

  /**
   * Render statistics card HTML
   *
   * @param label - Card label
   * @param value - Card value (number or string)
   * @returns HTML string for statistics card
   */
  renderStatisticsCard(label: string, value: number | string): string {
    return `      <div class="stat-card">
        <div class="stat-value">${escapeHtml(String(value))}</div>
        <div class="stat-label">${escapeHtml(label)}</div>
      </div>`;
  }

  /**
   * Render asset table HTML
   *
   * @param assets - Array of IP assets
   * @returns HTML string for asset table
   */
  private renderAssetTable(assets: IPAssetWithRelationships[]): string {
    if (assets.length === 0) {
      return '<p class="no-assets">No assets to display</p>';
    }

    const rows = assets.map((asset) => this.renderAssetRow(asset)).join('\n');

    return `    <div class="table-container">
      <table>
        <thead>
          <tr>
            <th>IP ID</th>
            <th>License Type</th>
            <th>Created</th>
            <th>Derivatives</th>
          </tr>
        </thead>
        <tbody>
${rows}
        </tbody>
      </table>
    </div>`;
  }

  /**
   * Render single asset row HTML
   *
   * @param asset - IP asset with relationships
   * @returns HTML string for table row
   */
  renderAssetRow(asset: IPAssetWithRelationships): string {
    const truncatedId = truncateIpId(asset.ipId);
    const formattedDate = formatDate(asset.createdAt);

    return `          <tr>
            <td class="ip-id-cell">
              <span class="ip-id" title="${escapeHtml(asset.ipId)}">${escapeHtml(truncatedId)}</span>
              <button class="copy-btn" onclick="copyToClipboard('${escapeHtml(asset.ipId)}')" title="Copy full IP ID">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                  <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"></path>
                </svg>
              </button>
            </td>
            <td>${escapeHtml(asset.licenseType)}</td>
            <td>${escapeHtml(formattedDate)}</td>
            <td>${asset.derivativeCount}</td>
          </tr>`;
  }

  /**
   * Get embedded CSS styles
   *
   * @returns Complete style block string
   */
  getEmbeddedStyles(): string {
    return `<style>
    :root {
      --bg-primary: #ffffff;
      --bg-secondary: #f5f5f5;
      --text-primary: #1a1a1a;
      --text-secondary: #666666;
      --accent: #4CAF50;
      --border: #e0e0e0;
    }

    @media (prefers-color-scheme: dark) {
      :root {
        --bg-primary: #1a1a1a;
        --bg-secondary: #2d2d2d;
        --text-primary: #ffffff;
        --text-secondary: #b0b0b0;
        --accent: #66BB6A;
        --border: #404040;
      }
    }

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      background-color: var(--bg-primary);
      color: var(--text-primary);
      line-height: 1.6;
      padding: 2rem;
      max-width: 1400px;
      margin: 0 auto;
    }

    header {
      text-align: center;
      margin-bottom: 3rem;
      padding-bottom: 2rem;
      border-bottom: 1px solid var(--border);
    }

    h1 {
      font-size: 2.5rem;
      font-weight: 600;
      margin-bottom: 0.5rem;
    }

    h2 {
      font-size: 1.5rem;
      font-weight: 500;
      margin-bottom: 1.5rem;
      color: var(--text-secondary);
    }

    .wallet {
      font-family: monospace;
      font-size: 1.1rem;
      color: var(--text-secondary);
      margin-bottom: 0.5rem;
    }

    .network-badge {
      display: inline-block;
      padding: 0.25rem 0.75rem;
      background-color: var(--accent);
      color: #fff;
      border-radius: 1rem;
      font-size: 0.875rem;
      font-weight: 500;
      text-transform: uppercase;
    }

    section {
      margin-bottom: 3rem;
    }

    .statistics {
      text-align: center;
    }

    .stats-grid {
      display: flex;
      flex-wrap: wrap;
      gap: 1rem;
      justify-content: center;
    }

    .stat-card {
      background-color: var(--bg-secondary);
      border: 1px solid var(--border);
      border-radius: 0.5rem;
      padding: 1.5rem 2rem;
      min-width: 150px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
    }

    .stat-value {
      font-size: 2rem;
      font-weight: 600;
      color: var(--accent);
    }

    .stat-label {
      font-size: 0.875rem;
      color: var(--text-secondary);
      margin-top: 0.25rem;
    }

    .graph {
      text-align: center;
    }

    .mermaid, .svg-fallback, .html-fallback, .no-graph {
      background-color: var(--bg-secondary);
      border: 1px solid var(--border);
      border-radius: 0.5rem;
      padding: 2rem;
      overflow-x: auto;
    }

    .no-graph {
      color: var(--text-secondary);
      font-style: italic;
    }

    .table-container {
      overflow-x: auto;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      background-color: var(--bg-secondary);
      border-radius: 0.5rem;
      overflow: hidden;
    }

    th, td {
      padding: 1rem;
      text-align: left;
      border-bottom: 1px solid var(--border);
    }

    th {
      background-color: var(--bg-primary);
      font-weight: 600;
      color: var(--text-secondary);
      text-transform: uppercase;
      font-size: 0.75rem;
      letter-spacing: 0.05em;
    }

    tbody tr:nth-child(even) {
      background-color: var(--bg-primary);
    }

    tbody tr:hover {
      background-color: rgba(76, 175, 80, 0.1);
    }

    .ip-id-cell {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }

    .ip-id {
      font-family: monospace;
      font-size: 0.9rem;
    }

    .copy-btn {
      background: none;
      border: 1px solid var(--border);
      border-radius: 0.25rem;
      padding: 0.25rem;
      cursor: pointer;
      color: var(--text-secondary);
      display: flex;
      align-items: center;
      justify-content: center;
      transition: all 0.2s;
    }

    .copy-btn:hover {
      background-color: var(--accent);
      border-color: var(--accent);
      color: #fff;
    }

    .copy-btn.copied {
      background-color: var(--accent);
      border-color: var(--accent);
      color: #fff;
    }

    .no-assets {
      text-align: center;
      color: var(--text-secondary);
      padding: 2rem;
      background-color: var(--bg-secondary);
      border-radius: 0.5rem;
    }

    footer {
      text-align: center;
      padding-top: 2rem;
      border-top: 1px solid var(--border);
      color: var(--text-secondary);
      font-size: 0.875rem;
    }

    footer a {
      color: var(--accent);
      text-decoration: none;
    }

    footer a:hover {
      text-decoration: underline;
    }

    /* Responsive breakpoints */
    @media (max-width: 1920px) {
      body {
        max-width: 1200px;
      }
    }

    @media (max-width: 1440px) {
      body {
        max-width: 1000px;
      }
    }

    @media (max-width: 768px) {
      body {
        padding: 1rem;
      }

      h1 {
        font-size: 2rem;
      }

      .stats-grid {
        flex-direction: column;
        align-items: center;
      }

      .stat-card {
        width: 100%;
        max-width: 300px;
      }

      .ip-id-cell {
        flex-direction: column;
        align-items: flex-start;
        gap: 0.25rem;
      }
    }

    @media (max-width: 375px) {
      body {
        padding: 0.5rem;
      }

      h1 {
        font-size: 1.5rem;
      }

      h2 {
        font-size: 1.25rem;
      }

      .stat-card {
        padding: 1rem;
      }

      .stat-value {
        font-size: 1.5rem;
      }

      th, td {
        padding: 0.5rem;
        font-size: 0.875rem;
      }
    }
  </style>`;
  }

  /**
   * Get embedded JavaScript for interactivity
   *
   * @returns Complete script block string
   */
  getEmbeddedScript(): string {
    return `<script>
    mermaid.initialize({ startOnLoad: true });

    function copyToClipboard(text) {
      navigator.clipboard.writeText(text).then(function() {
        // Find the button that was clicked
        var buttons = document.querySelectorAll('.copy-btn');
        buttons.forEach(function(btn) {
          if (btn.onclick && btn.onclick.toString().includes(text)) {
            btn.classList.add('copied');
            var originalHTML = btn.innerHTML;
            btn.innerHTML = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg>';
            setTimeout(function() {
              btn.classList.remove('copied');
              btn.innerHTML = originalHTML;
            }, 1500);
          }
        });
      }).catch(function(err) {
        console.error('Failed to copy: ', err);
      });
    }

    // Add click listeners after DOM is loaded
    document.addEventListener('DOMContentLoaded', function() {
      var buttons = document.querySelectorAll('.copy-btn');
      buttons.forEach(function(btn) {
        btn.addEventListener('click', function(e) {
          e.preventDefault();
        });
      });
    });
  </script>`;
  }
}
